name = "job-tracker-oauth"
main = "worker.mjs"
compatibility_date = "2024-11-20"

# Replace the id below with your real KV namespace ID
kv_namespaces = [
  { binding = "JOBS_KV", id = "PUT_YOUR_PROD_KV_NAMESPACE_ID_HERE" }
]

[vars]
# Comma-separated list of allowed front-end origins (prod + local)
ALLOWED_ORIGIN = "https://samanbahrampoor.github.io,http://localhost:5173"
ALLOWED_LOGIN = "samanbahrampoor"
PUBLIC_URL = "https://job-tracker-oauth.saman-bahrampoor.workers.dev"
# (Optional) You can set GITHUB_CLIENT_ID here (non-secret). The secret still works too.
# GITHUB_CLIENT_ID = "YOUR_GITHUB_OAUTH_CLIENT_ID"

# ---- Optional DEV environment (keeps prod KV safe during local dev) ----
[env.dev]
kv_namespaces = [
  { binding = "JOBS_KV", id = "PUT_YOUR_DEV_KV_NAMESPACE_ID_HERE" }
]

[env.dev.vars]
ALLOWED_ORIGIN = "http://localhost:5173"
PUBLIC_URL = "https://job-tracker-oauth-dev.saman-bahrampoor.workers.dev"
