# wrangler.toml
# Update the kv_namespaces IDs with your actual values from:
#   wrangler kv:namespace create JOB_STATE
# (Use a separate preview_id for dev if you like.)

name = "job-tracker-worker"
main = "worker.mjs"
compatibility_date = "2025-08-01"

[[kv_namespaces]]
binding = "JOB_STATE"
id = "b581e095c8be4d8d9ac46b9f9639fe52"
preview_id = "01ec05a83b004714a613d03359d2ed21"

# If you use a custom domain/route, uncomment and set a route:
# routes = [
#   { pattern = "api.samanb.dev/api/*", zone_name = "samanb.dev" }
# ]
