# wrangler.toml
# Update the kv_namespaces IDs with your actual values from:
#   wrangler kv:namespace create JOB_STATE
# (Use a separate preview_id for dev if you like.)

name = "job-tracker-worker"
main = "worker.mjs"
compatibility_date = "2025-08-01"

[[kv_namespaces]]
binding = "JOB_STATE"
id = "REPLACE_WITH_PROD_NAMESPACE_ID"
preview_id = "REPLACE_WITH_DEV_NAMESPACE_ID"

# If you use a custom domain/route, uncomment and set a route:
# routes = [
#   { pattern = "api.samanb.dev/api/*", zone_name = "samanb.dev" }
# ]
