name = "job-tracker-oauth"
main = "worker.mjs"
compatibility_date = "2024-11-20"

kv_namespaces = [
  # Production KV namespace (already exists per your deploy output)
  { binding = "JOBS_KV", id = "c1ecd7041c424e1588508bfe8f6f3288" }
]

[vars]
# Allow calls from your GitHub Pages origin
ALLOWED_ORIGIN = "https://samanbahrampoor.github.io"
# Optional allow-list: only this GitHub username may sign in (remove to allow anyone)
ALLOWED_LOGIN = "samanbahrampoor"
# Optional informational URL if you reference it anywhere
PUBLIC_URL = "https://job-tracker-oauth.saman-bahrampoor.workers.dev"

# ---------- Optional: separate DEV env so wrangler dev doesn't touch prod KV ----------
# 1) Create another KV namespace in dashboard/CLI
# 2) Put its id below
[env.dev]
kv_namespaces = [
  { binding = "JOBS_KV", id = "01ec05a83b004714a613d03359d2ed21" }
]
[env.dev.vars]
ALLOWED_ORIGIN = "http://localhost:5173"
PUBLIC_URL = "https://job-tracker-oauth-dev.saman-bahrampoor.workers.dev"
